### ISSUE TITLE
Help needed.

### ISSUE THREAD

**Issue by ZEkA10000** [VirtuallTek/FFSi18n#1]
I translated FF Studio with QT Linguist but how to put language into FF Studio? 
(tried to put in root, lang/ru-ru/, languages/ru-ru/, translations/qm__ru, translation/ru_ru/)

**Comment by VirtuallTek** [comment]
Make a copy of the en-us folder and rename to ru-ru. Edit Info.xml and fill it with the language and your information. Place all translated files in this folder and you're done (must be the .qm file produced by File / Release, not the .ts ones).
You can include the Qt translation too from here: [qt_ru.zip](https://github.com/VirtuallTek/FFSi18n/files/7875523/qt_ru.zip)

To install on Fighter Factory you must put it inside the languages folder. The location varies based on the host OS:
**- Windows:** C:\ProgramData\Fighter Factory Studio;
**- Linux:** /usr/local/share/Fighter Factory Studio;
**- macOS X:** /Contents/Resources inside the App Blundle.

**Comment by ZEkA10000** [comment]
Then I think you need to update README.md because before your answer I'd can't find any clues where I could put translations.
